on: push
jobs:
  test-install-cli:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v2
        with:
          version: "latest"

      - name: Verify installation
        run: op --version
  test-load-secrets:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@v2
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          SECRET: op://app-cicd/hello-world/secret

      - name: Print masked secret
        run: 'echo "Secret: ${{ steps.op-load-secret.outputs.SECRET }}"'
        # Prints: Secret: ***
